# Generated by Django 5.1.2 on 2024-12-13 12:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtistMasterAdditional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(blank=True, max_length=100, null=True)),
                ('lastname', models.CharField(blank=True, max_length=100, null=True)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('country', models.CharField(blank=True, choices=[('India', 'India'), ('USA', 'USA'), ('Canada', 'Canada'), ('UK', 'UK'), ('Australia', 'Australia')], max_length=100, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('description', models.CharField(blank=True, choices=[('Writer', 'Writer'), ('Publisher', 'Publisher'), ('Editor', 'Editor'), ('Poet', 'Poet'), ('Essayist', 'Essayist'), ('Novelist', 'Novelist'), ('Blogger', 'Blogger'), ('Short Story Writer', 'Short Story Writer'), ('Motivational Speaker', 'Motivational Speaker'), ('Spiritual Leader', 'Spiritual Leader'), ('Literary Critic', 'Literary Critic')], max_length=100, null=True)),
                ('introduction', models.TextField(blank=True, null=True)),
                ('languages_read', models.TextField(blank=True, null=True)),
                ('languages_write', models.TextField(blank=True, null=True)),
                ('languages_speak', models.TextField(blank=True, null=True)),
                ('facebook_link', models.URLField(blank=True, null=True)),
                ('instagram_link', models.URLField(blank=True, null=True)),
                ('linkedin_link', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
