# Generated by Django 5.1.2 on 2024-12-13 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_artistmasteradditional'),
    ]

    operations = [
        migrations.AddField(
            model_name='artistmasteradditional',
            name='availability',
            field=models.CharField(blank=True, choices=[('full_time', 'Full-time'), ('part_time', 'Part-time'), ('freelance', 'Freelance')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='artistmasteradditional',
            name='awards',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='artistmasteradditional',
            name='certifications',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='artistmasteradditional',
            name='company_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='artistmasteradditional',
            name='experience',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='artistmasteradditional',
            name='job_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='artistmasteradditional',
            name='portfolio',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='artistmasteradditional',
            name='primary_skills',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='artistmasteradditional',
            name='published_works',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='artistmasteradditional',
            name='secondary_skills',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='artistmasteradditional',
            name='short_bio',
            field=models.TextField(blank=True, null=True),
        ),
    ]
