# Generated by Django 5.1.2 on 2024-12-14 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_artistmasteradditional_aadhar_back_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='artistmasteradditional',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/'),
        ),
    ]
