# Generated by Django 5.1.2 on 2024-12-24 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_experience_alter_artistmasteradditional_experience_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.ImageField(blank=True, null=True, upload_to='gallery/')),
            ],
        ),
        migrations.RemoveField(
            model_name='artistmasteradditional',
            name='experience_details',
        ),
        migrations.AddField(
            model_name='artistmasteradditional',
            name='images',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='myapp.gallery'),
        ),
        migrations.AddField(
            model_name='artistmasteradditional',
            name='experience_details',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='artist_experiences', to='myapp.experience'),
        ),
    ]
