# Generated by Django 5.1.2 on 2024-12-24 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_gallery_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artistmasteradditional',
            name='experience_details',
        ),
        migrations.RemoveField(
            model_name='artistmasteradditional',
            name='images',
        ),
        migrations.AddField(
            model_name='artistmasteradditional',
            name='experience_details',
            field=models.ManyToManyField(blank=True, related_name='artist_experiences', to='myapp.experience'),
        ),
        migrations.AddField(
            model_name='artistmasteradditional',
            name='images',
            field=models.ManyToManyField(blank=True, related_name='images', to='myapp.gallery'),
        ),
    ]
