# Generated by Django 5.1.2 on 2024-12-26 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_remove_artistmasteradditional_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artistmasteradditional',
            name='city',
        ),
    ]
