# Generated by Django 5.1.2 on 2024-12-28 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_remove_artistmasteradditional_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='artistmasteradditional',
            name='books_published',
            field=models.TextField(blank=True, null=True),
        ),
    ]
