# Generated by Django 5.1.2 on 2024-12-28 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_artistmasteradditional_books_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='artistmasteradditional',
            name='highest_qualification',
            field=models.TextField(blank=True, null=True),
        ),
    ]
