# Generated by Django 5.1.2 on 2025-01-03 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_alter_bookspublished_book_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='artistmasteradditional',
            name='twitter_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
