# Generated by Django 5.1.2 on 2025-01-04 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_artistmasteradditional_twitter_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookspublished',
            name='book_image',
            field=models.ImageField(blank=True, null=True, upload_to='book_images/'),
        ),
    ]
