# Generated by Django 5.1.2 on 2025-01-05 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_remove_artistmasteradditional_firstname_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instituteName', models.CharField(max_length=255)),
                ('qualification', models.CharField(max_length=255)),
                ('yearOfPassing', models.DateField()),
            ],
        ),
        migrations.RemoveField(
            model_name='artistmasteradditional',
            name='highest_qualification',
        ),
        migrations.AddField(
            model_name='artistmasteradditional',
            name='education_details',
            field=models.ManyToManyField(blank=True, related_name='artist_education', to='myapp.education'),
        ),
    ]
