# Generated by Django 5.1.2 on 2025-01-06 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0024_alter_education_yearofpassing'),
    ]

    operations = [
        migrations.CreateModel(
            name='Awards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('award_name', models.CharField(max_length=255)),
                ('award_year', models.CharField(blank=True, max_length=10, null=True)),
                ('award_image', models.ImageField(blank=True, null=True, upload_to='award_images/')),
            ],
        ),
        migrations.AddField(
            model_name='artistmasteradditional',
            name='awards_received',
            field=models.ManyToManyField(blank=True, related_name='artist_awards', to='myapp.awards'),
        ),
    ]
