# Generated by Django 5.1.2 on 2025-01-06 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0025_awards_artistmasteradditional_awards_received'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=255)),
                ('blog_date', models.DateField(auto_now_add=True)),
                ('blog_banner', models.ImageField(upload_to='blog_banners/')),
                ('blog_heading', models.CharField(max_length=100)),
                ('blog_body', models.TextField(max_length=3000)),
                ('blog_tags', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'Blog',
                'verbose_name_plural': 'Blogs',
            },
        ),
    ]
