# Generated by Django 5.1.2 on 2025-01-07 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0028_awards_award_by_organisation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artistmasteradditional',
            name='awards',
        ),
        migrations.RemoveField(
            model_name='artistmasteradditional',
            name='certifications',
        ),
        migrations.RemoveField(
            model_name='artistmasteradditional',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='artistmasteradditional',
            name='published_works',
        ),
        migrations.AlterField(
            model_name='awards',
            name='award_by_organisation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
