# Generated by Django 5.1.2 on 2025-01-07 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0029_remove_artistmasteradditional_awards_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artistmasteradditional',
            name='availability',
        ),
    ]
