# Generated by Django 5.1.2 on 2025-01-07 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0030_remove_artistmasteradditional_availability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artistmasteradditional',
            name='description',
            field=models.CharField(blank=True, choices=[('Writer', 'Writer'), ('Publisher', 'Publisher'), ('Editor', 'Editor'), ('Poet', 'Poet'), ('Printer', 'Printer'), ('Standup Comedian', 'Standup Comedian'), ('Compere/Emcee', 'Compere/Emcee'), ('Essayist', 'Essayist'), ('Book Store Owner', 'Book Store Owner'), ('Digital Marketplace/Platform', 'Digital Marketplace/Platform'), ('Novelist', 'Novelist'), ('Artist', 'Artist'), ('Social Media Influencer', 'Social Media Influencer'), ('Blogger', 'Blogger'), ('Entertainment Troupe Owner', 'Entertainment Troupe Owner'), ('Short Story Writer', 'Short Story Writer'), ('Digital Marketer', 'Digital Marketer'), ('Motivational Speaker', 'Motivational Speaker'), ('Digital Graphics Designer', 'Digital Graphics Designer'), ('Event Manager', 'Event Manager'), ('Columnist', 'Columnist'), ('Journalist', 'Journalist'), ('Digital Content Creator', 'Digital Content Creator'), ('Spiritual Leader', 'Spiritual Leader'), ('Public Relations Manager', 'Public Relations Manager'), ('Literary Critic', 'Literary Critic'), ('Literary Reviewer', 'Literary Reviewer'), ('Lyricist', 'Lyricist'), ('Scriptwriter-Drama', 'Scriptwriter-Drama'), ('Scriptwriter-Screen', 'Scriptwriter-Screen'), ('Translator', 'Translator')], max_length=100, null=True),
        ),
    ]
