# Generated by Django 5.1.2 on 2025-01-09 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0032_awards_award_category_awards_award_sub_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='awards',
            name='award_image',
        ),
        migrations.CreateModel(
            name='AwardImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('award_image', models.ImageField(blank=True, null=True, upload_to='award_images/')),
                ('award', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='myapp.awards')),
            ],
        ),
    ]
