# Generated by Django 5.1.2 on 2025-01-09 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0033_remove_awards_award_image_awardimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookspublished',
            name='book_image',
        ),
        migrations.CreateModel(
            name='BookImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_image', models.ImageField(blank=True, null=True, upload_to='book_images/')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_images', to='myapp.bookspublished')),
            ],
        ),
    ]
