# Generated by Django 5.1.2 on 2025-01-17 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0034_remove_bookspublished_book_image_bookimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='artistmasterbasic',
            name='admin_access',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='artistmasterbasic',
            name='admin_type',
            field=models.CharField(blank=True, choices=[('Super Admin', 'Super Admin'), ('Normal Admin', 'Normal Admin')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='artistmasterbasic',
            name='admin_username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
