# Generated by Django 5.1.2 on 2025-01-17 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0035_artistmasterbasic_admin_access_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='artistmasterbasic',
            name='plaintext_password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
